<<<<<<< HEAD
[phases.setup]
nixPkgs = ["php84", "php84Extensions.mbstring", "php84Extensions.pdo", "php84Extensions.pdo_mysql", "php84Extensions.openssl", "php84Extensions.tokenizer", "php84Extensions.xml", "php84Extensions.ctype", "php84Extensions.fileinfo", "php84Extensions.bcmath", "php84Extensions.curl", "nodejs"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev", "npm install", "npm run build"]

[start]
=======
[phases.setup]
nixPkgs = ["php84", "php84Extensions.mbstring", "php84Extensions.pdo", "php84Extensions.pdo_mysql", "php84Extensions.openssl", "php84Extensions.tokenizer", "php84Extensions.xml", "php84Extensions.ctype", "php84Extensions.fileinfo", "php84Extensions.bcmath", "php84Extensions.curl"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev"]

[start]
>>>>>>> 5c57147 (fix build config)
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"